window_step_ms: 10
train_dir: /root/sun-wakeword/trained_models/sun_v2
features:
- features_dir: /root/sun-wakeword/data/v2_features/positive
  sampling_weight: 2.5
  penalty_weight: 1.0
  truth: true
  truncation_strategy: truncate_start
  type: mmap
- features_dir: /root/sun-wakeword/data/v2_features/sberdevices
  sampling_weight: 12.0
  penalty_weight: 1.5
  truth: false
  truncation_strategy: random
  type: mmap
- features_dir: /root/sun-wakeword/data/v2_features/openstt
  sampling_weight: 12.0
  penalty_weight: 1.5
  truth: false
  truncation_strategy: random
  type: mmap
- features_dir: /root/sun-wakeword/data/negative_datasets/speech
  sampling_weight: 5.0
  penalty_weight: 1.0
  truth: false
  truncation_strategy: random
  type: mmap
- features_dir: /root/sun-wakeword/data/negative_datasets/dinner_party
  sampling_weight: 8.0
  penalty_weight: 1.0
  truth: false
  truncation_strategy: random
  type: mmap
- features_dir: /root/sun-wakeword/data/negative_datasets/no_speech
  sampling_weight: 6.0
  penalty_weight: 1.0
  truth: false
  truncation_strategy: random
  type: mmap
- features_dir: /root/sun-wakeword/data/negative_datasets/dinner_party_eval
  sampling_weight: 0.0
  penalty_weight: 1.0
  truth: false
  truncation_strategy: split
  type: mmap
training_steps:
- 8000
- 5000
positive_class_weight:
- 1
- 1
negative_class_weight:
- 22
- 26
learning_rates:
- 0.001
- 0.0005
batch_size: 128
time_mask_max_size:
- 0
- 2
time_mask_count:
- 0
- 1
freq_mask_max_size:
- 0
- 2
freq_mask_count:
- 0
- 1
eval_step_interval: 500
clip_duration_ms: 1500
target_minimization: 0.9
minimization_metric: null
maximization_metric: average_viable_recall
